use_frameworks!

source 'https://github.com/morapelker/tedooo-pod-repo.git'
#source 'https://github.com/CocoaPods/Specs.git'
source 'https://cdn.cocoapods.org/'

target 'TedoooOnBoardingScreen_Tests' do
  pod 'TedoooOnBoardingScreen', :path => '../'
  
  pod 'Quick', '~> 2.2.0'
    pod 'Nimble', '~> 10.0.0'
end
